# Generated by Django 6.0.3 on 2026-04-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_donation_accepted_by_donation_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='delivery_person',
        ),
    ]
